fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
hering:
    resource: "@HeringBundle/Controller/"
    type:     annotation
    prefix:   /

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
